# Generated by Django 3.1.2 on 2021-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authorfirst',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='authorlast',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
